name: 'Sync with upstream'

on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo repo_name=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}') >> $GITHUB_ENV
        echo upstream_branch=$(echo "$GITHUB_REF_NAME" | awk -F / '{print $2}') >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: "wikimedia/${{ env.repo_name }}"
        source_branch: ${{ env.upstream_branch }}
        destination_branch: weirdgloop/repo-sync
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: weirdgloop/repo-sync
        destination_branch: ${{ github.ref_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Sync with upstream"